# 配置文件版本，如果不熟悉这个是干啥的请不要修改。
Version: 1.0-SNAPSHOT
# 自动更新配置文件
# [true - 开启 / false - 关闭]
AutoUpDate: true
# 自动将OP添加到可执行人员名单中（后台不受这个限制）
# [true - 开启 / false - 关闭]
AutoOpToUserName: false
# 调试开关
# 开启后会输出大量的日志消息，如果没有遇到问题请不要开启
Debug: false