name: SystemCall
version: 0.7-SNAPSHOT
main: vip.bingzi.systemcall.SystemCall
api-version: "1.13"
softdepend: [PlaceholderAPI]
authors: [BingZi, jianjianai]
description: "一个调用系统组件的Minecraft插件。"
commands:
  SystemCall:
    aliases:
      - sc
      - system
      - call
    description: "呼叫系统指令，可以添加参数以调用操作系统组件。"
    permission: SystemCall.op
    permission-message: "操作系统组件的权限，如果没有必要请不要将这个权限给予任何玩家。"
permissions:
  SystemCall.op:
    default: op
    description: "操作系统组件的权限，如果没有必要请不要将这个权限给予任何玩家。"
